# Generated by Django 3.2.6 on 2021-09-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='profile_pic',
            new_name='profilePic',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='profile_pic',
            new_name='profilePic',
        ),
    ]
